### ISSUE TITLE
Add sample SDF file for the bike inventory

### ISSUE THREAD

**Issue by tngTUDOR** [mrvisscher/bw-scenarios#3]
# Expected

- [ ] Create a sample inventory for the activity (from the ground up) example nb
- [ ] generate an `SDF` file and add it to the repository under the notebooks directory

**Comment by marc-vdm** [comment]
solved in https://github.com/mrvisscher/bw-scenarios/commit/95ef5c706b56869a8cd9aca8f627d2e448931e1a
